### PR TITLE
Issue qa

### LINKED ISSUE #2: Issue Created For QA
This is the issue created for QA.

### PR DESCRIPTION
**Pull request by huanhuiying**

### CODE REVIEW

**Review by amanda-chan — APPROVED** [review]
nice nice

**Review by claris0911 — APPROVED** [review]
noice

**Review by meganpng — APPROVED** [review]
nice

**Comment by huanhuiying** [comment]
closes #10

**Comment by huanhuiying** [comment]
Closes #10

**Comment by amanda-chan** [comment]
hello

**Review by amanda-chan — APPROVED** [review]
nice work!

**Review by huanhuiying — COMMENTED** [review]
i approved

**Review by claris0911 — APPROVED** [review]
noice

**Comment by huanhuiying** [comment]
ok, we will proceed

**Comment by huanhuiying** [comment]
ok, we will proceed #10

**Comment by huanhuiying** [comment]
i linked it #10

**Pull request merged**
